"use client";

import { useState } from "react";
import { signIn, signUp, ApiError, User } from "@/lib/api";

interface AuthScreenProps {
  onAuth: (user: User) => void;
}

export default function AuthScreen({ onAuth }: AuthScreenProps) {
  const [mode, setMode] = useState<"signin" | "signup">("signin");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setLoading(true);
    try {
      const user = mode === "signin"
        ? await signIn(email, password)
        : await signUp(email, password);
      onAuth(user);
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.message);
      } else {
        setError("Something went wrong. Please try again.");
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center px-4">
      <div className="w-full max-w-sm">
        <h1
          className="text-3xl font-bold text-center mb-2"
          style={{ color: "#032147" }}
        >
          Prelegal
        </h1>
        <p className="text-center text-gray-500 text-sm mb-8">
          {mode === "signin" ? "Sign in to your account" : "Create a new account"}
        </p>

        <form
          onSubmit={handleSubmit}
          className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm"
        >
          {error && (
            <p className="text-red-600 text-sm mb-4">{error}</p>
          )}

          <label className="block mb-4">
            <span className="block text-sm font-medium text-gray-700 mb-1">Email</span>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm text-gray-900 placeholder:text-gray-400 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none"
              placeholder="you@example.com"
            />
          </label>

          <label className="block mb-6">
            <span className="block text-sm font-medium text-gray-700 mb-1">Password</span>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              minLength={6}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm text-gray-900 placeholder:text-gray-400 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none"
              placeholder="At least 6 characters"
            />
          </label>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-2 text-white text-sm font-medium rounded-md disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            style={{ backgroundColor: "#753991" }}
          >
            {loading
              ? (mode === "signin" ? "Signing in..." : "Creating account...")
              : (mode === "signin" ? "Sign In" : "Sign Up")}
          </button>
        </form>

        <p className="text-center text-sm text-gray-500 mt-4">
          {mode === "signin" ? (
            <>
              Don&apos;t have an account?{" "}
              <button
                onClick={() => { setMode("signup"); setError(null); }}
                className="font-medium"
                style={{ color: "#209dd7" }}
              >
                Sign up
              </button>
            </>
          ) : (
            <>
              Already have an account?{" "}
              <button
                onClick={() => { setMode("signin"); setError(null); }}
                className="font-medium"
                style={{ color: "#209dd7" }}
              >
                Sign in
              </button>
            </>
          )}
        </p>
      </div>

      <p className="mt-12 text-xs text-gray-400 text-center max-w-md">
        Documents generated by Prelegal are drafts for informational purposes
        only and are subject to professional legal review. They do not
        constitute legal advice.
      </p>
    </div>
  );
}
